# See https://pre-commit.com for more information
# Install: poetry run pre-commit install
# Run on all files: poetry run pre-commit run -a

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies: []

  # mypy (型チェック) - use local mypy.ini and check package only
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy
        args:
          - "--config-file=mypy.ini"
          - "-p"
          - "real_estate_mcp"
        pass_filenames: false
        additional_dependencies: []

  # Markdown Lint (Node 環境を pre-commit が自動生成)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        name: markdownlint
        args:
          - "--ignore"
          - "htmlcov"
          - "--disable"
          - "MD013"  # 行長制限は README で緩和

  # Pylint (静的解析) - src 配下を対象
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.7
    hooks:
      - id: pylint
        name: pylint
        args:
          - "-j"
          - "0"
          - "src/real_estate_mcp"
        additional_dependencies: []
