name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint (Black & isort)
        run: |
          poetry run black --check .
          poetry run isort --check-only .

      - name: Lint (flake8)
        run: |
          poetry run flake8 .

      - name: Type check (mypy)
        run: |
          poetry run mypy src/real_estate_mcp

      - name: Run tests & coverage
        run: |
          poetry run pytest --cov=src/real_estate_mcp --cov-report=xml --cov-report=term-missing

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
